### ISSUE TITLE
Erro## level stuck zombies

### ISSUE THREAD

**Issue by Ketz1337** [nuclearsilo583/ze_deadcore_v1_3-insane-champion-knightmare-stripper#1]
Erro## level stuck zombies in round start

setpos 0.000000 -960.000000 10036.931641;setang 15.698574 6.292609 0.000000

![stuckerro](https://user-images.githubusercontent.com/23225942/129450269-a28a4d34-9761-4cac-83db-704f8fcac88c.jpg)

**Comment by nuclearsilo583** [comment]
Thanks for reporting. Fixed on new commit. Have fun
